


POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
    "username": "doesitwork",
    "password": "kaoschording"
}

################################
POST http://127.0.0.1:8000/api/auth/register
Content-Type: application/json

{
    "username": "doesitwork",
    "email": "works@example.com",
    "password": "kaoschording"
}

################################

{
  "user": {
    "id": 8,
    "username": "fuckingtest",
    "email": "ftes@example.com"
  },
  "token": "70057e7cd7375574ab9feda1c1231956869ec27f9f03fcd9ff0b59df9b6149d8"
}

#########
POST http://127.0.0.1:8000/api/auth/logout
Authorization: Token 8ea70a2cf39c8d4b4bae38da69db5e12ab0e9c9227b8a4f58f498fd12ffbae3e

################################

GET http://127.0.0.1:8000/api/auth/user
Authorization: Token

###

POST http://127.0.0.1:8000/api/auth/register
Content-Type: application/json

{
    "username": "",
    "email": "",
    "password": ""
}

###

POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
    "username": "",
    "password": ""
}

###

POST http://127.0.0.1:8000/api/auth/logout
Authorization: Token
