# Generated by Django 3.1.1 on 2021-04-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezfap', '0004_auto_20210330_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleep',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='bedin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='wakeup',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
